name: Automated Releases

on:
  workflow_dispatch:
  push:
    paths:
      - src/**
      - build.gradle
      - gradle.properties
      - settings.gradle
      - gradle/**
      - gradlew
      - gradlew.bat
      - versioning.gradle

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Gradle Permissions
        run: chmod +x ./gradlew

      - name: Run Data Generation
        run: ./gradlew runDatagen

      - name: Build
        run: ./gradlew build

      - name: Discord Webhook Publish
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.VF_BUILDS }}
          filename: 'build/libs/valeries-food-1.0.0.jar'
          username: Valerie's Foods
          content: New Valerie's Foods GitHub Release Available!

      - name: Get version
        id: get_version
        run: echo "::set-output name=version::$(grep 'version' gradle.properties | cut -d'=' -f2 | tr -d ' ')"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          body: |
            Automated release for `Valerie's Foods` build `#${{ github.run_number }}`.
          files: build/libs/*
          draft: false
          prerelease: false
